## New Weights after one update: Using TensorFlow weight update
----------

optimizer = tf.train.GradientDescentOptimizer(1e-5).minimize(lossCE)

In [ ]:
import tensorflow as tf
import numpy as np

batch_size = 4
dim = 3
hidden_units = 4

ops.reset_default_graph()
sess = tf.Session()

with sess.as_default():
    x = tf.placeholder(dtype=tf.float32, shape=[None, dim], name="x")
    y = tf.placeholder(dtype=tf.int32, shape=[None], name="y")
    w = tf.Variable(initial_value=tf.random_normal(shape=[dim, hidden_units], seed=432), name="w")
    b = tf.Variable(initial_value=tf.zeros(shape=[hidden_units]), name="b")
    
    print ('The initial weights initilized are: \n')
    print (tf.cast(tf.random_normal(shape=[dim, hidden_units], seed=432), dtype=tf.float32).eval())
    print ('')
    print ('The initial bais initilized are: \n')
    print (tf.cast(tf.zeros(shape=[hidden_units]), dtype=tf.int32).eval())
    print ('')
    
    logits = tf.nn.tanh(tf.matmul(x, w) + b)
    cross_entropy = tf.nn.sparse_softmax_cross_entropy_with_logits(logits=logits, labels=y, name="xentropy")
    lossCE = tf.reduce_mean(cross_entropy) 
    optimizer = tf.train.GradientDescentOptimizer(1e-5).minimize(lossCE)
        
    print ('Begin training Begin training Begin training Begin training Begin training ')
    print ('')
    
    np.random.seed(398)
    data = np.random.randn(batch_size, dim)
    labels = np.random.randint(0, hidden_units, size=batch_size)
    sess.run(tf.global_variables_initializer())
    newW, newB, _ = sess.run([w, b, optimizer], feed_dict={x:data, y:labels})

    print (newW)
    print ('')
    print (newB)
    
sess.close()

The initial weights initilized are: 

[[-2.11875319  1.11074173 -1.60225117 -1.04866672]
 [ 1.0743587  -0.37837428 -0.39874253  1.21538258]
 [ 0.70911169 -0.10536155 -1.4022162  -0.44625875]]

The initial bais initilized are: 

[0 0 0 0]

Begin training Begin training Begin training Begin training Begin training 

[[-2.11875176  1.1107409  -1.60225093 -1.04867029]
 [ 1.07435918 -0.37837315 -0.39874318  1.21537995]
 [ 0.70911378 -0.10536345 -1.40221572 -0.44625914]]

[  6.51314224e-07  -1.33663309e-06   4.03212113e-07   2.65411586e-06]


## New Weights after one update: Manual Update:
* gradients = tf.gradients(lossCE, tf.trainable_variables())
* gradients_and_vars = list(zip(gradients, tf.trainable_variables()))

* for g, v in gradients_and_vars:
   * if g is not None:
    *    newVar = v - 1e-5*(g)

In [84]:
import tensorflow as tf
import numpy as np

batch_size = 4
dim = 3
hidden_units = 4

ops.reset_default_graph()
sess = tf.Session()

with sess.as_default():
    x = tf.placeholder(dtype=tf.float32, shape=[None, dim], name="x")
    y = tf.placeholder(dtype=tf.int32, shape=[None], name="y")
    w = tf.Variable(initial_value=tf.random_normal(shape=[dim, hidden_units], seed=432), name="w")
    b = tf.Variable(initial_value=tf.zeros(shape=[hidden_units]), name="b")
    
    print ('The initial weights initilized are: \n')
    print (tf.cast(tf.random_normal(shape=[dim, hidden_units], seed=432), dtype=tf.float32).eval())
    print ('')
    print ('The initial bais initilized are: \n')
    print (tf.cast(tf.zeros(shape=[hidden_units]), dtype=tf.int32).eval())
    print ('')
    
    
    logits = tf.nn.tanh(tf.matmul(x, w) + b)
    cross_entropy = tf.nn.sparse_softmax_cross_entropy_with_logits(logits=logits, labels=y, name="xentropy")
    lossCE = tf.reduce_mean(cross_entropy)
    optimizer = tf.train.GradientDescentOptimizer(1e-5)
    
    print ('Begin training Begin training Begin training Begin training Begin training ')
    print ('')
    
    grads_and_vars = optimizer.compute_gradients(cross_entropy, tf.trainable_variables())
    gradients = tf.gradients(lossCE, tf.trainable_variables())
    gradients_and_vars = list(zip(gradients, tf.trainable_variables()))
    print ([v.name for v in tf.trainable_variables()])
    # generate data
    
    np.random.seed(398)
    data = np.random.randn(batch_size, dim)
    labels = np.random.randint(0, hidden_units, size=batch_size)
    
    # RUN SESSION:
    sess.run(tf.global_variables_initializer())
    Grads_and_Vars, Gradients_and_Vars, Gradients = sess.run([grads_and_vars, gradients_and_vars, gradients], feed_dict={x:data, y:labels})
    print ("Grads_and_Vars when using optimizer: \n",Grads_and_Vars)
    print ('')
    print ("Gradients_and_Vars when NOT using optimizer: \n", Gradients_and_Vars)
    print ('')
    print ("Gradients when NOT using optimizer: \n", Gradients)
    print ('')
    print ('')

    for varNum, (g, v) in enumerate(Gradients_and_Vars):
#         print (varNum)
        print ('Running for Variable Num ', variableNames[varNum])
        if g is not None:
            print ("**************** this is variable *************")
            print ("variable's shape:")
            print (v)
            print ("**************** this is gradient *************")
            print ("gradient's shape:",)
            print (g)
            
            print ('')
            print ('The new Variable looks like')
            newVar = v - 1e-5*(g)
            print (newVar)
            print('')
            print ('')


sess.close()

The initial weights initilized are: 

[[-2.11875319  1.11074173 -1.60225117 -1.04866672]
 [ 1.0743587  -0.37837428 -0.39874253  1.21538258]
 [ 0.70911169 -0.10536155 -1.4022162  -0.44625875]]

The initial bais initilized are: 

[0 0 0 0]

Begin training Begin training Begin training Begin training Begin training 

['w:0', 'b:0']
Grads_and_Vars when using optimizer: 
 [(array([[-0.58818352,  0.34526709, -0.08834551,  1.42918241],
       [-0.18376471, -0.45474505,  0.26138756,  1.02784896],
       [-0.82264823,  0.7613858 , -0.178047  ,  0.16059123]], dtype=float32), array([[-2.11875319,  1.11074173, -1.60225117, -1.04866672],
       [ 1.0743587 , -0.37837428, -0.39874253,  1.21538258],
       [ 0.70911169, -0.10536155, -1.4022162 , -0.44625875]], dtype=float32)), (array([-0.2605257 ,  0.53465325, -0.16128485, -1.06164634], dtype=float32), array([ 0.,  0.,  0.,  0.], dtype=float32))]

Gradients_and_Vars when NOT using optimizer: 
 [(array([[-0.14704588,  0.08631677, -0.02208638,  0.35729

# Experimenting the above situation with 2 layers:
------------

## New Weights after one update: Using TensorFlow weight update
----------

optimizer = tf.train.GradientDescentOptimizer(1e-5).minimize(lossCE)

In [88]:
import tensorflow as tf
import numpy as np

batch_size = 4
dim = 3
hidden_units1 = 4
hidden_units2 = 4

ops.reset_default_graph()
sess = tf.Session()

with sess.as_default():
    x = tf.placeholder(dtype=tf.float32, shape=[None, dim], name="x")
    y = tf.placeholder(dtype=tf.int32, shape=[None], name="y")
    w1 = tf.Variable(initial_value=tf.random_normal(shape=[dim, hidden_units1], seed=432), name="w1")
    b1 = tf.Variable(initial_value=tf.zeros(shape=[hidden_units1]), name="b1")
    w2 = tf.Variable(initial_value=tf.random_normal(shape=[hidden_units1, hidden_units2], seed=989), name="w2")
    b2 = tf.Variable(initial_value=tf.zeros(shape=[hidden_units2]), name="b2") 
    
    print ('The initial weights (w1) initilized are: \n')
    print (tf.cast(tf.random_normal(shape=[dim, hidden_units], seed=432), dtype=tf.float32).eval())
    print ('')
    print ('The initial bais (b1) initilized are: \n')
    print (tf.cast(tf.zeros(shape=[hidden_units]), dtype=tf.int32).eval())
    print ('')
    print ('The initial weights (w2) initilized are: \n')
    print (tf.cast(tf.random_normal(shape=[dim, hidden_units], seed=989), dtype=tf.float32).eval())
    print ('')
    print ('The initial bais (b1) initilized are: \n')
    print (tf.cast(tf.zeros(shape=[hidden_units]), dtype=tf.int32).eval())
    print ('')
    
    
    logits1 = tf.nn.tanh(tf.matmul(x, w1) + b1)
    logits2 = tf.nn.tanh(tf.matmul(logits1, w2) + b2)
    
    ################
    cross_entropy = tf.nn.sparse_softmax_cross_entropy_with_logits(logits=logits2, labels=y, name="xentropy")
    lossCE = tf.reduce_mean(cross_entropy) 
    optimizer = tf.train.GradientDescentOptimizer(1e-5).minimize(lossCE)
    ################
    
    print ('Begin training Begin training Begin training Begin training Begin training ')
    print ('')
    
    np.random.seed(398)
    data = np.random.randn(batch_size, dim)
    labels = np.random.randint(0, hidden_units2, size=batch_size)
    sess.run(tf.global_variables_initializer())
    newW1, newB1, newW2, newB2, _ = sess.run([w1, b1, w2, b2, optimizer], feed_dict={x:data, y:labels})

    print (newW1)
    print ('')
    print (newB1)
    print ('')
    print (newW2)
    print ('')
    print (newB2)
    
sess.close()

The initial weights (w1) initilized are: 

[[-2.11875319  1.11074173 -1.60225117 -1.04866672]
 [ 1.0743587  -0.37837428 -0.39874253  1.21538258]
 [ 0.70911169 -0.10536155 -1.4022162  -0.44625875]]

The initial bais (b1) initilized are: 

[0 0 0 0]

The initial weights (w2) initilized are: 

[[-2.11875319  1.11074173 -1.60225117 -1.04866672]
 [ 1.0743587  -0.37837428 -0.39874253  1.21538258]
 [ 0.70911169 -0.10536155 -1.4022162  -0.44625875]]

The initial bais (b1) initilized are: 

[0 0 0 0]

Begin training Begin training Begin training Begin training Begin training 

[[-2.11875319  1.11074126 -1.60225117 -1.0486691 ]
 [ 1.07435882 -0.37837431 -0.39874256  1.21538115]
 [ 0.70911139 -0.10536185 -1.4022162  -0.44625914]]

[ -3.27776860e-07   1.07476318e-07   2.79387002e-08   1.60490333e-06]

[[-2.11875343  1.11074054 -1.60225117 -1.04866552]
 [ 1.07435882 -0.37837321 -0.39874253  1.2153815 ]
 [ 0.70911151 -0.10536274 -1.4022162  -0.44625753]
 [-0.02040439 -1.24266374 -0.77951401  1.51996

In [105]:
import tensorflow as tf
import numpy as np

batch_size = 4
dim = 3
hidden_units1 = 4
hidden_units2 = 4

ops.reset_default_graph()
sess = tf.Session()

with sess.as_default():
    x = tf.placeholder(dtype=tf.float32, shape=[None, dim], name="x")
    y = tf.placeholder(dtype=tf.int32, shape=[None], name="y")
    w1 = tf.Variable(initial_value=tf.random_normal(shape=[dim, hidden_units1], seed=432), name="w1")
    b1 = tf.Variable(initial_value=tf.zeros(shape=[hidden_units1]), name="b1")
    w2 = tf.Variable(initial_value=tf.random_normal(shape=[hidden_units1, hidden_units2], seed=989), name="w2")
    b2 = tf.Variable(initial_value=tf.zeros(shape=[hidden_units2]), name="b2") 
    
    print ('The initial weights (w1) initilized are: \n')
    print (tf.cast(tf.random_normal(shape=[dim, hidden_units], seed=432), dtype=tf.float32).eval())
    print ('')
    print ('The initial bais (b1) initilized are: \n')
    print (tf.cast(tf.zeros(shape=[hidden_units]), dtype=tf.int32).eval())
    print ('')
    print ('The initial weights (w2) initilized are: \n')
    print (tf.cast(tf.random_normal(shape=[dim, hidden_units], seed=989), dtype=tf.float32).eval())
    print ('')
    print ('The initial bais (b1) initilized are: \n')
    print (tf.cast(tf.zeros(shape=[hidden_units]), dtype=tf.int32).eval())
    print ('')
    
    
    logits1 = tf.nn.tanh(tf.matmul(x, w1) + b1)
    logits2 = tf.nn.tanh(tf.matmul(logits1, w2) + b2)
    
    
    #################
    cross_entropy = tf.nn.sparse_softmax_cross_entropy_with_logits(logits=logits2, labels=y, name="xentropy")
    lossCE = tf.reduce_mean(cross_entropy)
    optimizer = tf.train.GradientDescentOptimizer(1e-5)
    #################
    
    print ('Begin training Begin training Begin training Begin training Begin training ')
    print ('')
    
    # Fetching variables to manually caluculate the new weights
    grads_and_vars = optimizer.compute_gradients(cross_entropy, tf.trainable_variables())
    gradients = tf.gradients(lossCE, tf.trainable_variables())
    gradients_and_vars = list(zip(gradients, tf.trainable_variables()))
    variableNames = [v.name for v in tf.trainable_variables()]
    # generate data
    
    np.random.seed(398)
    data = np.random.randn(batch_size, dim)
    labels = np.random.randint(0, hidden_units2, size=batch_size)
    
    # RUN SESSION:
    sess.run(tf.global_variables_initializer())
    Grads_and_Vars, Gradients_and_Vars, Gradients = sess.run([grads_and_vars, gradients_and_vars, gradients], feed_dict={x:data, y:labels})
    print ("Grads_and_Vars when using optimizer: \n",Grads_and_Vars)
    print ('')
    print ("Gradients_and_Vars when NOT using optimizer: \n", Gradients_and_Vars)
    print ('')
    print ("Gradients when NOT using optimizer: \n", Gradients)
    print ('')
    print ('')

    for varNum, (g, v) in enumerate(Gradients_and_Vars):
#         print (varNum)
        print ('Running for Variable Num ', variableNames[varNum])
        if g is not None:
#             print ("**************** this is variable *************")
#             print ("variable's shape:")
#             print (v)
#             print ("**************** this is gradient *************")
#             print ("gradient's shape:",)
#             print (g)
            
            print ('')
            print ('The new Variable looks like')
            newVar = v - 1e-5*(g)
            print (newVar)
            print('')
            print ('')

sess.close()

The initial weights (w1) initilized are: 

[[-2.11875319  1.11074173 -1.60225117 -1.04866672]
 [ 1.0743587  -0.37837428 -0.39874253  1.21538258]
 [ 0.70911169 -0.10536155 -1.4022162  -0.44625875]]

The initial bais (b1) initilized are: 

[0 0 0 0]

The initial weights (w2) initilized are: 

[[-2.41577721 -0.75244576  2.13699627  0.52897286]
 [-0.88196027 -1.1298064  -0.1327185   1.08851182]
 [-1.2091223  -0.32934931  0.72396326 -0.67482239]]

The initial bais (b1) initilized are: 

[0 0 0 0]

Begin training Begin training Begin training Begin training Begin training 

Grads_and_Vars when using optimizer: 
 [(array([[ 0.12204197,  0.44748574, -0.02048684,  0.27312103],
       [ 0.08219481,  0.30057651,  0.03871645,  0.2215021 ],
       [ 0.06438579,  0.06360757, -0.02989684,  0.00324626]], dtype=float32), array([[-2.11875319,  1.11074173, -1.60225117, -1.04866672],
       [ 1.0743587 , -0.37837428, -0.39874253,  1.21538258],
       [ 0.70911169, -0.10536155, -1.4022162 , -0.44625875]], 