In [2]:
from __future__ import division
from __future__ import print_function

import numpy as np
import tensorflow as tf

In [3]:
# Let us start a interactive session
####################################
# An interactive session. Ones Interactive session is called 
# then it means that the session we used to intiate the interactice 
# console would be the default session used to perform all the tensor operation

sess = tf.InteractiveSession()

# BATCH NORM:

Batch norm is a technique to 

In [58]:


N, D = x.shape

mu = 1./N * np.sum(x, axis = 0)

print (mu)

xmu = x - mu

print (xmu)

sq = xmu ** 2

print (sq)

[ 2.5  3.5  4.5]
[[-1.5 -1.5 -1.5]
 [ 1.5  1.5  1.5]]
[[ 2.25  2.25  2.25]
 [ 2.25  2.25  2.25]]


In [67]:
x = np.array([[1,2,3],[4,5,6]])

def batchnorm_forward(x, gamma=None, beta=None, eps=None):
    N, D = x.shape
    print (x.shape, x)
    #step1: calculate mean
    mu = 1./N * np.sum(x, axis = 0)
    print (mu.shape, mu)
    
    #step2: subtract mean vector of every trainings example
    xmu = x - mu
    print (xmu.shape, xmu)
    
    #step3: following the lower branch - calculation denominator
    sq = xmu ** 2
    print (sq.shape, sq)
    
    #step4: calculate variance
    var = 1./N * np.sum(sq, axis = 0)
    print (var.shape, var)
    
    #step5: add eps for numerical stability, then sqrt
    sqrtvar = np.sqrt(var + eps)
    print (sqrtvar.shape, sqrtvar)
    
    #step6: invert sqrtwar
    ivar = 1./sqrtvar
    print (ivar.shape, ivar)
    
    #step7: execute normalization
    xhat = xmu * ivar
    print (xhat.shape, xhat)
    
    #step8: Nor the two transformation steps
    gammax = gamma * xhat
    print (gammax.shape, gammax)
    
    #step9
    out = gammax + beta
    print (out.shape, out)
#     #store intermediate
#     cache = (xhat,gamma,xmu,ivar,sqrtvar,var,eps)
    
#     return out, cache


batchnorm_forward(x, gamma = np.array([0.01, 0.001, 0.0001]), beta=np.array([1,2,3]), eps = 0.01)

(2, 3) [[1 2 3]
 [4 5 6]]
(3,) [ 2.5  3.5  4.5]
(2, 3) [[-1.5 -1.5 -1.5]
 [ 1.5  1.5  1.5]]
(2, 3) [[ 2.25  2.25  2.25]
 [ 2.25  2.25  2.25]]
(3,) [ 2.25  2.25  2.25]
(3,) [ 1.50332964  1.50332964  1.50332964]
(3,) [ 0.66519011  0.66519011  0.66519011]
(2, 3) [[-0.99778516 -0.99778516 -0.99778516]
 [ 0.99778516  0.99778516  0.99778516]]
(2, 3) [[ -9.97785158e-03  -9.97785158e-04  -9.97785158e-05]
 [  9.97785158e-03   9.97785158e-04   9.97785158e-05]]
(2, 3) [[ 0.99002215  1.99900221  2.99990022]
 [ 1.00997785  2.00099779  3.00009978]]


In [56]:
a = np.array([[[1,2,3],
               [2,3,4],
               [4,5,6]],
              [[4,3,2],
               [2,3,1],
               [1,1,1]]
             ], dtype="float64")
print ('The shape of a is ', a.shape)
print ('sum along 0 axis \n', np.sum(a, axis=0))
print ('sum along 1 axis \n', np.sum(a, axis=1))
print ('sum along 2 axis \n', np.sum(a, axis=2))
sum_a1 = sum(sum(sum(a)))
print (sum_a1/19)
# print (sum(sum_a1))
# print ('')
# prin 
print (a.shape)
tf_a = tf.stack(a)

# tf_a = tf.Variable(a, shape=tf.get_shape())
print (tf_a.eval())
print (tf_a.get_shape())

# get the moment 
batchMean, batchVar = tf.nn.moments(tf_a, [0,1,2], name='moments')
print (batchMean.eval(), batchVar.eval())
ema = tf.train.ExponentialMovingAverage(decay=0.5)
print (ema)

The shape of a is  (2, 3, 3)
sum along 0 axis 
 [[ 5.  5.  5.]
 [ 4.  6.  5.]
 [ 5.  6.  7.]]
sum along 1 axis 
 [[  7.  10.  13.]
 [  7.   7.   4.]]
sum along 2 axis 
 [[  6.   9.  15.]
 [  9.   6.   3.]]
2.52631578947
(2, 3, 3)
[[[ 1.  2.  3.]
  [ 2.  3.  4.]
  [ 4.  5.  6.]]

 [[ 4.  3.  2.]
  [ 2.  3.  1.]
  [ 1.  1.  1.]]]
(2, 3, 3)
2.66666666667 2.11111111111


In [ ]:
from collections import defaultdict
m = {}
n = {} 
newDict = defaultdict(list)
m['a'] = np.array([[1,2,3],[-1,3,-4]], dtype=float)
n['a'] = np.array([[3,4,3],[-1,3,-4]], dtype=float)


# print (np.abs(a-b))
# print (np.sum(np.abs(a-b)))

m['b'] = np.array([[5,4,1],[7,8,9]], dtype=float)
n['b'] = np.array([[9,9,5],[-2,1,2]], dtype=float)

for layer,val in n.items():
    print (layer)
    print (np.abs(val-m[layer]))
    print (np.sum(np.abs(val-m[layer])))
    print ('')
    newDict[layer].append(np.sum(np.abs(val-m[layer])))
    
print (newDict)

In [1]:
from __future__ import division
from __future__ import print_function
import os
import cv2
import numpy as np
import imutils
import pickle
import random
from skimage.feature import hog
from sklearn.decomposition import PCA

In [3]:
class HOG:
    def __init__(self, featureParams): 
        self.orienations = featureParams['orientations']
        self.pixelsPerCell = featureParams['pixelsPerCell']
        self.cellsPerBlock = featureParams['cellsPerBlock']
        self.block_norm = featureParams['block_norm']
        self.visualise = featureParams['visualise']
        self.transform_sqrt = featureParams['transform_sqrt']

    def describe(self, image):
        # Use transform_sqrt for Power law Compression before processing the image to increase the accuracy
        # Use visualise to return the image of the histogram
        if self.visualise:
            hist, hog_image = hog(image,
                                orientations = self.orienations,
                                pixels_per_cell = self.pixelsPerCell,
                                cells_per_block = self.cellsPerBlock,
                                visualise= self.visualise,
                                transform_sqrt = self.transform_sqrt)
            return hist, hog_image
        else:
            hog_image = hog(image,
                                orientations = self.orienations,
                                pixels_per_cell = self.pixelsPerCell,
                                cells_per_block = self.cellsPerBlock,
                                transform_sqrt = self.transform_sqrt)
            return hog_image

In [48]:
class Preprocess(): 
    
    def __init__(self):        
        featureParams1 = dict(orientations = 9, pixelsPerCell = (6, 6), cellsPerBlock = (1, 1), block_norm = 'L1', visualise = False, transform_sqrt = True)
        featureParams2 = dict(orientations = 9, pixelsPerCell = (5, 10), cellsPerBlock = (1, 1), block_norm = 'L1', visualise = False, transform_sqrt = True)
        featureParams3 = dict(orientations = 9, pixelsPerCell = (10, 5), cellsPerBlock = (1, 1), block_norm = 'L1', visualise = False, transform_sqrt = True)
        
        featureParams4 = dict(orientations = 18, pixelsPerCell = (6, 6), cellsPerBlock = (1, 1), block_norm = 'L1', visualise = False, transform_sqrt = True)
        featureParams5 = dict(orientations = 18, pixelsPerCell = (5, 10), cellsPerBlock = (1, 1), block_norm = 'L1', visualise = False, transform_sqrt = True)
        featureParams6 = dict(orientations = 18, pixelsPerCell = (10, 5), cellsPerBlock = (1, 1), block_norm = 'L1', visualise = False, transform_sqrt = True)
        
        
        featureParams7 = dict(orientations = 9, pixelsPerCell = (6, 6), cellsPerBlock = (3, 3), block_norm = 'L1', visualise = False, transform_sqrt = True)
        featureParams8 = dict(orientations = 9, pixelsPerCell = (5, 10), cellsPerBlock = (1, 4), block_norm = 'L1', visualise = False, transform_sqrt = True)
        featureParams9 = dict(orientations = 9, pixelsPerCell = (10, 5), cellsPerBlock = (5, 2), block_norm = 'L1', visualise = False, transform_sqrt = True)
        
        featureParams10 = dict(orientations = 18, pixelsPerCell = (6, 6), cellsPerBlock = (3, 3), block_norm = 'L1', visualise = False, transform_sqrt = True)
        featureParams11 = dict(orientations = 18, pixelsPerCell = (5, 10), cellsPerBlock = (2, 5), block_norm = 'L1', visualise = False, transform_sqrt = True)
        featureParams12 = dict(orientations = 18, pixelsPerCell = (10, 5), cellsPerBlock = (5, 2), block_norm = 'L1', visualise = False, transform_sqrt = True)
        
        featureParams13 = dict(orientations = 18, pixelsPerCell = (5, 10), cellsPerBlock = (1, 1), block_norm = 'L1', visualise = False, transform_sqrt = True)
        featureParams14 = dict(orientations = 18, pixelsPerCell = (10, 5), cellsPerBlock = (1, 1), block_norm = 'L1', visualise = False, transform_sqrt = True)
        

        self.obj_HOG_p1 = HOG(featureParams1)
        self.obj_HOG_p2 = HOG(featureParams2)
        self.obj_HOG_p3 = HOG(featureParams3)
        self.obj_HOG_p4 = HOG(featureParams4)
        self.obj_HOG_p5 = HOG(featureParams5)
        self.obj_HOG_p6 = HOG(featureParams6)
        self.obj_HOG_p7 = HOG(featureParams7)
        self.obj_HOG_p8 = HOG(featureParams8)
        self.obj_HOG_p9 = HOG(featureParams9)
        self.obj_HOG_p10 = HOG(featureParams10)
        self.obj_HOG_p11 = HOG(featureParams11)
        self.obj_HOG_p12 = HOG(featureParams12)
        self.obj_HOG_p13 = HOG(featureParams13)
        self.obj_HOG_p14 = HOG(featureParams14)
#         self.obj_HOG_p15 = HOG(featureParams15)
#         self.obj_HOG_p3_3 = HOG(featureParams3_3)
#         self.obj_HOG_p3_4 = HOG(featureParams3_4)
        
        
        
    def featureExtractor (self, imagePath):
        # Fetch the image into matrix form
        img = cv2.imread(imagePath)

        # Note tensor flow Fetches image in BGR format, hence converting it into RGB
        imgRGB = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

        # Convert the Image into Gray Scale
        imgGS = cv2.cvtColor(imgRGB, cv2.COLOR_RGB2GRAY) 
        
        imgGS_crop = imgGS[1:31, 1:31]

        # Find the HOG features corresponding the parameter setting 1
        imgHOGp1 = self.obj_HOG_p1.describe(imgGS_crop)
        imgHOGp2 = self.obj_HOG_p2.describe(imgGS_crop)
        imgHOGp3 = self.obj_HOG_p3.describe(imgGS_crop)
        imgHOGp4 = self.obj_HOG_p4.describe(imgGS_crop)
        imgHOGp5 = self.obj_HOG_p5.describe(imgGS_crop)
        imgHOGp6 = self.obj_HOG_p6.describe(imgGS_crop)
        imgHOGp7 = self.obj_HOG_p7.describe(imgGS_crop)
        imgHOGp8 = self.obj_HOG_p8.describe(imgGS_crop)
        imgHOGp9 = self.obj_HOG_p9.describe(imgGS_crop)
        imgHOGp10 = self.obj_HOG_p10.describe(imgGS_crop)
        imgHOGp11 = self.obj_HOG_p11.describe(imgGS_crop)
        imgHOGp12 = self.obj_HOG_p12.describe(imgGS_crop)
        imgHOGp13 = self.obj_HOG_p13.describe(imgGS_crop)
        imgHOGp14 = self.obj_HOG_p14.describe(imgGS_crop)
#         imgHOGp15 = self.obj_HOG_p11.describe(imgGS_crop)

        return (imgHOGp1,imgHOGp2,imgHOGp3,imgHOGp4,imgHOGp5,imgHOGp6,imgHOGp7,imgHOGp8,imgHOGp9,imgHOGp10,imgHOGp11,imgHOGp12,imgHOGp13,imgHOGp14)

airplane_datapath = "/Users/sam/All-Program/App-DataSet/Kaggle-Challenges/CIFAR-10/trainDataAirplane/"
cat_datapath = "/Users/sam/All-Program/App-DataSet/Kaggle-Challenges/CIFAR-10/trainDataCat/"
ImageDir = [airplane_datapath, cat_datapath]

for image_dir in ImageDir:
    objectName = os.path.basename(os.path.normpath(image_dir))
    filenameArr =  os.listdir(image_dir)
    for numImage, image in enumerate(filenameArr):
        imagePath = os.path.join(image_dir, image)
        print (imagePath)
        obj_Preprocess = Preprocess()
        (imgHOGp1,imgHOGp2,imgHOGp3,imgHOGp4,imgHOGp5,
         imgHOGp6,imgHOGp7,imgHOGp8,imgHOGp9,imgHOGp10, 
         imgHOGp11,imgHOGp12,imgHOGp13,imgHOGp14) = obj_Preprocess.featureExtractor(imagePath)
        print (imgHOGp1.shape)
        print (imgHOGp2.shape)
        print (imgHOGp3.shape)
        print ('##################')
        print (imgHOGp4.shape)
        print (imgHOGp5.shape)
        print (imgHOGp6.shape)
        print ('##################')
        print (imgHOGp7.shape)
        print (imgHOGp8.shape)
        print (imgHOGp9.shape)
        print ('##################')
        print (imgHOGp10.shape)
        print (imgHOGp11.shape)
        print (imgHOGp12.shape)
        print ('##################')
        print (imgHOGp13.shape)
        print (imgHOGp14.shape)
        break
    break

/Users/sam/All-Program/App-DataSet/Kaggle-Challenges/CIFAR-10/trainDataAirplane/10009.png


ValueError: negative dimensions are not allowed